# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_api_core_v1_persistent_volume_claim_spec import IoK8sApiCoreV1PersistentVolumeClaimSpec


class TestIoK8sApiCoreV1PersistentVolumeClaimSpec(unittest.TestCase):
    """ IoK8sApiCoreV1PersistentVolumeClaimSpec unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1PersistentVolumeClaimSpec(self):
        """
        Test IoK8sApiCoreV1PersistentVolumeClaimSpec
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_api_core_v1_persistent_volume_claim_spec.IoK8sApiCoreV1PersistentVolumeClaimSpec()
        pass


if __name__ == '__main__':
    unittest.main()
