# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.post_user import PostUser


class TestPostUser(unittest.TestCase):
    """ PostUser unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostUser(self):
        """
        Test PostUser
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.post_user.PostUser()
        pass


if __name__ == '__main__':
    unittest.main()
