# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_status_details import IoK8sApimachineryPkgApisMetaV1StatusDetails


class TestIoK8sApimachineryPkgApisMetaV1StatusDetails(unittest.TestCase):
    """ IoK8sApimachineryPkgApisMetaV1StatusDetails unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1StatusDetails(self):
        """
        Test IoK8sApimachineryPkgApisMetaV1StatusDetails
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_status_details.IoK8sApimachineryPkgApisMetaV1StatusDetails()
        pass


if __name__ == '__main__':
    unittest.main()
