# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_api_core_v1_key_to_path import IoK8sApiCoreV1KeyToPath


class TestIoK8sApiCoreV1KeyToPath(unittest.TestCase):
    """ IoK8sApiCoreV1KeyToPath unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1KeyToPath(self):
        """
        Test IoK8sApiCoreV1KeyToPath
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_api_core_v1_key_to_path.IoK8sApiCoreV1KeyToPath()
        pass


if __name__ == '__main__':
    unittest.main()
