# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_owner_reference import IoK8sApimachineryPkgApisMetaV1OwnerReference


class TestIoK8sApimachineryPkgApisMetaV1OwnerReference(unittest.TestCase):
    """ IoK8sApimachineryPkgApisMetaV1OwnerReference unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1OwnerReference(self):
        """
        Test IoK8sApimachineryPkgApisMetaV1OwnerReference
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_owner_reference.IoK8sApimachineryPkgApisMetaV1OwnerReference()
        pass


if __name__ == '__main__':
    unittest.main()
