# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_api_core_v1_service_list import IoK8sApiCoreV1ServiceList


class TestIoK8sApiCoreV1ServiceList(unittest.TestCase):
    """ IoK8sApiCoreV1ServiceList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1ServiceList(self):
        """
        Test IoK8sApiCoreV1ServiceList
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_api_core_v1_service_list.IoK8sApiCoreV1ServiceList()
        pass


if __name__ == '__main__':
    unittest.main()
