# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_apimachinery_pkg_version_info import IoK8sApimachineryPkgVersionInfo


class TestIoK8sApimachineryPkgVersionInfo(unittest.TestCase):
    """ IoK8sApimachineryPkgVersionInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgVersionInfo(self):
        """
        Test IoK8sApimachineryPkgVersionInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_apimachinery_pkg_version_info.IoK8sApimachineryPkgVersionInfo()
        pass


if __name__ == '__main__':
    unittest.main()
