# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """ UsersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.users_api.UsersApi()

    def tearDown(self):
        pass

    def test_users_get(self):
        """
        Test case for users_get

        
        """
        pass

    def test_users_id_delete(self):
        """
        Test case for users_id_delete

        
        """
        pass

    def test_users_id_get(self):
        """
        Test case for users_id_get

        
        """
        pass

    def test_users_id_patch(self):
        """
        Test case for users_id_patch

        
        """
        pass

    def test_users_post(self):
        """
        Test case for users_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
