# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_api_core_v1_pod_security_context import IoK8sApiCoreV1PodSecurityContext


class TestIoK8sApiCoreV1PodSecurityContext(unittest.TestCase):
    """ IoK8sApiCoreV1PodSecurityContext unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1PodSecurityContext(self):
        """
        Test IoK8sApiCoreV1PodSecurityContext
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_api_core_v1_pod_security_context.IoK8sApiCoreV1PodSecurityContext()
        pass


if __name__ == '__main__':
    unittest.main()
