# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.get_user import GetUser


class TestGetUser(unittest.TestCase):
    """ GetUser unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUser(self):
        """
        Test GetUser
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.get_user.GetUser()
        pass


if __name__ == '__main__':
    unittest.main()
