# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_api_apps_v1_deployment import IoK8sApiAppsV1Deployment


class TestIoK8sApiAppsV1Deployment(unittest.TestCase):
    """ IoK8sApiAppsV1Deployment unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAppsV1Deployment(self):
        """
        Test IoK8sApiAppsV1Deployment
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_api_apps_v1_deployment.IoK8sApiAppsV1Deployment()
        pass


if __name__ == '__main__':
    unittest.main()
