# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.io_k8s_apimachinery_pkg_api_resource_quantity import IoK8sApimachineryPkgApiResourceQuantity


class TestIoK8sApimachineryPkgApiResourceQuantity(unittest.TestCase):
    """ IoK8sApimachineryPkgApiResourceQuantity unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApiResourceQuantity(self):
        """
        Test IoK8sApimachineryPkgApiResourceQuantity
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.io_k8s_apimachinery_pkg_api_resource_quantity.IoK8sApimachineryPkgApiResourceQuantity()
        pass


if __name__ == '__main__':
    unittest.main()
