# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.clusters_api import ClustersApi


class TestClustersApi(unittest.TestCase):
    """ ClustersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.clusters_api.ClustersApi()

    def tearDown(self):
        pass

    def test_clusters_get(self):
        """
        Test case for clusters_get

        
        """
        pass

    def test_clusters_id_delete(self):
        """
        Test case for clusters_id_delete

        
        """
        pass

    def test_clusters_id_get(self):
        """
        Test case for clusters_id_get

        
        """
        pass

    def test_clusters_id_kubeconfig_get(self):
        """
        Test case for clusters_id_kubeconfig_get

        
        """
        pass

    def test_clusters_id_patch(self):
        """
        Test case for clusters_id_patch

        
        """
        pass

    def test_clusters_id_status_get(self):
        """
        Test case for clusters_id_status_get

        
        """
        pass

    def test_clusters_post(self):
        """
        Test case for clusters_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
