# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Addon(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'link': 'str',
        'icon': 'str'
    }

    attribute_map = {
        'name': 'name',
        'link': 'link',
        'icon': 'icon'
    }

    def __init__(self, name=None, link=None, icon=None):
        """
        Addon - a model defined in Swagger
        """

        self._name = None
        self._link = None
        self._icon = None

        if name is not None:
          self.name = name
        if link is not None:
          self.link = link
        if icon is not None:
          self.icon = icon

    @property
    def name(self):
        """
        Gets the name of this Addon.

        :return: The name of this Addon.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Addon.

        :param name: The name of this Addon.
        :type: str
        """

        self._name = name

    @property
    def link(self):
        """
        Gets the link of this Addon.

        :return: The link of this Addon.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """
        Sets the link of this Addon.

        :param link: The link of this Addon.
        :type: str
        """

        self._link = link

    @property
    def icon(self):
        """
        Gets the icon of this Addon.

        :return: The icon of this Addon.
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """
        Sets the icon of this Addon.

        :param icon: The icon of this Addon.
        :type: str
        """

        self._icon = icon

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Addon):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
