# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetUser(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'username': 'str',
        'email': 'str',
        'password': 'str',
        'organization': 'Organization'
    }

    attribute_map = {
        'id': 'id',
        'username': 'username',
        'email': 'email',
        'password': 'password',
        'organization': 'organization'
    }

    def __init__(self, id=None, username=None, email=None, password=None, organization=None):
        """
        GetUser - a model defined in Swagger
        """

        self._id = None
        self._username = None
        self._email = None
        self._password = None
        self._organization = None

        if id is not None:
          self.id = id
        if username is not None:
          self.username = username
        if email is not None:
          self.email = email
        if password is not None:
          self.password = password
        if organization is not None:
          self.organization = organization

    @property
    def id(self):
        """
        Gets the id of this GetUser.

        :return: The id of this GetUser.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this GetUser.

        :param id: The id of this GetUser.
        :type: str
        """

        self._id = id

    @property
    def username(self):
        """
        Gets the username of this GetUser.

        :return: The username of this GetUser.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this GetUser.

        :param username: The username of this GetUser.
        :type: str
        """

        self._username = username

    @property
    def email(self):
        """
        Gets the email of this GetUser.

        :return: The email of this GetUser.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this GetUser.

        :param email: The email of this GetUser.
        :type: str
        """

        self._email = email

    @property
    def password(self):
        """
        Gets the password of this GetUser.

        :return: The password of this GetUser.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this GetUser.

        :param password: The password of this GetUser.
        :type: str
        """

        self._password = password

    @property
    def organization(self):
        """
        Gets the organization of this GetUser.

        :return: The organization of this GetUser.
        :rtype: Organization
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """
        Sets the organization of this GetUser.

        :param organization: The organization of this GetUser.
        :type: Organization
        """

        self._organization = organization

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
