# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class IoK8sApiCoreV1ContainerStateWaiting(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'reason': 'str'
    }

    attribute_map = {
        'message': 'message',
        'reason': 'reason'
    }

    def __init__(self, message=None, reason=None):
        """
        IoK8sApiCoreV1ContainerStateWaiting - a model defined in Swagger
        """

        self._message = None
        self._reason = None

        if message is not None:
          self.message = message
        if reason is not None:
          self.reason = reason

    @property
    def message(self):
        """
        Gets the message of this IoK8sApiCoreV1ContainerStateWaiting.
        Message regarding why the container is not yet running.

        :return: The message of this IoK8sApiCoreV1ContainerStateWaiting.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this IoK8sApiCoreV1ContainerStateWaiting.
        Message regarding why the container is not yet running.

        :param message: The message of this IoK8sApiCoreV1ContainerStateWaiting.
        :type: str
        """

        self._message = message

    @property
    def reason(self):
        """
        Gets the reason of this IoK8sApiCoreV1ContainerStateWaiting.
        (brief) reason the container is not yet running.

        :return: The reason of this IoK8sApiCoreV1ContainerStateWaiting.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """
        Sets the reason of this IoK8sApiCoreV1ContainerStateWaiting.
        (brief) reason the container is not yet running.

        :param reason: The reason of this IoK8sApiCoreV1ContainerStateWaiting.
        :type: str
        """

        self._reason = reason

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, IoK8sApiCoreV1ContainerStateWaiting):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
