# coding: utf-8

"""
    Kubernetes Queen API

    A simple API to interact with Kubernetes clusters

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PostCluster(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'provisioner': 'str',
        'state': 'str',
        'kubeconfig': 'object',
        'metadata': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'provisioner': 'provisioner',
        'state': 'state',
        'kubeconfig': 'kubeconfig',
        'metadata': 'metadata'
    }

    def __init__(self, id=None, name=None, provisioner=None, state=None, kubeconfig=None, metadata=None):
        """
        PostCluster - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._provisioner = None
        self._state = None
        self._kubeconfig = None
        self._metadata = None

        if id is not None:
          self.id = id
        self.name = name
        self.provisioner = provisioner
        if state is not None:
          self.state = state
        if kubeconfig is not None:
          self.kubeconfig = kubeconfig
        if metadata is not None:
          self.metadata = metadata

    @property
    def id(self):
        """
        Gets the id of this PostCluster.

        :return: The id of this PostCluster.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PostCluster.

        :param id: The id of this PostCluster.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this PostCluster.

        :return: The name of this PostCluster.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PostCluster.

        :param name: The name of this PostCluster.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def provisioner(self):
        """
        Gets the provisioner of this PostCluster.
        Reference to related Provisioner

        :return: The provisioner of this PostCluster.
        :rtype: str
        """
        return self._provisioner

    @provisioner.setter
    def provisioner(self, provisioner):
        """
        Sets the provisioner of this PostCluster.
        Reference to related Provisioner

        :param provisioner: The provisioner of this PostCluster.
        :type: str
        """
        if provisioner is None:
            raise ValueError("Invalid value for `provisioner`, must not be `None`")

        self._provisioner = provisioner

    @property
    def state(self):
        """
        Gets the state of this PostCluster.

        :return: The state of this PostCluster.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this PostCluster.

        :param state: The state of this PostCluster.
        :type: str
        """
        allowed_values = ["OK", "Error", "Deploying", "Destroying", "Unknown"]
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def kubeconfig(self):
        """
        Gets the kubeconfig of this PostCluster.
        Kubeconfig file in JSON format

        :return: The kubeconfig of this PostCluster.
        :rtype: object
        """
        return self._kubeconfig

    @kubeconfig.setter
    def kubeconfig(self, kubeconfig):
        """
        Sets the kubeconfig of this PostCluster.
        Kubeconfig file in JSON format

        :param kubeconfig: The kubeconfig of this PostCluster.
        :type: object
        """

        self._kubeconfig = kubeconfig

    @property
    def metadata(self):
        """
        Gets the metadata of this PostCluster.

        :return: The metadata of this PostCluster.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """
        Sets the metadata of this PostCluster.

        :param metadata: The metadata of this PostCluster.
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PostCluster):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
